#!/usr/bin/env bash

. git-sh-setup
export GIT_DIR

if [ -d "${GIT_DIR}/annex" ] # timeout 2s git annex info >/dev/null 2>&
then
    if [ -e "${GIT_DIR}/hooks/post-merge" ]
    then
        "${GIT_DIR}/hooks/post-merge"
    else
        # automatically configured by git-annex
        git annex smudge --update
    fi
fi
