#!/usr/bin/env bash
#
# An example hook script to verify what is about to be committed
# by applypatch from an e-mail message.
#
# The hook should exit with non-zero status after issuing an
# appropriate message if it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-applypatch".

. git-sh-setup


if [ -e .githooks/annex/stop.sh ]
then
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1
    then
      # Check if it is a git-annex repository
      if [ -d "${GIT_DIR}/annex" ] # timeout 2s git annex info >/dev/null 2>&
      then
        if [ -r "${GIT_DIR}/annex/daemon.pid" ] && xargs ps < "${GIT_DIR}/annex/daemon.pid" || .githooks/annex/git-annex-assistant-allowed.sh
        then
          .githooks/annex/stop.sh $(cat "${GIT_DIR}/annex/daemon.pid")
          echo "$0: ⚠️  WARNING: stopping git annex assistant."
        else
          echo "$0: ✅ NOTICE: git annex assistant not running."
        fi
        if [ -e "${GIT_DIR}/hooks/pre-applypatch"  ]
        then
          "${GIT_DIR}/hooks/pre-applypatch"
        else
          echo No git annex command for hooks/pre-applypatch >/dev/null 2>&1
        fi
      fi
  fi
fi


precommit=".githooks/pre-commit"
test -x "$precommit" && exec "$precommit" ${1+"$@"}
:
